version: "3.0"
services:
  esb:
    image: docker.wso2.com/wso2esb:5.0.0
    container_name: esb
    ports:
      - 9443:9443
      - 8280:8280
    networks:
      bridge-net:
        ipv4_address: 169.69.69.2

  das:
    image: chinthakaak/wso2das:3.1.0
    container_name: das
    ports:
      - 9444:9444
      - 8281:8281
    networks:
      bridge-net:
        ipv4_address: 169.69.69.3

  device:
    image : chinthakaak/nodered:iot-slim
    container_name: device
    ports:
      - 1880:1880
    volumes:
      - D:\data\git_projects\krdl\volumes\iot-conf:/data
    networks:
      bridge-net:
        ipv4_address: 169.69.69.4

  client:
    image: tomcat:9-alpine
    container_name: client
    ports:
      - 8082:8080
    volumes:
      - D:\\data\\kraydel\\codebaseui\\kraydel\\Kraydel-client\\WebContent:/usr/local/tomcat/webapps/Kraydel-client
    networks:
      bridge-net:
        ipv4_address: 169.69.69.5

  postgres:
    image: postgres:10.1
    container_name: postgres
    ports:
      - 5432:5432
    networks:
      bridge-net:
        ipv4_address: 169.69.69.6
    volumes:
      - pgdata:/var/lib/postgresql/data

  mysql:
    image: mysql:8.0.3
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - 3306:3306
    networks:
      bridge-net:
        ipv4_address: 169.69.69.7

  server:
    image: openjdk:8-alpine
    container_name: server
    working_dir: /mnt/kraydel-platform
    depends_on:
      - postgres
    volumes:
      - D:\data\kraydel\codebase1\kraydel\kraydel-platform\kraydel-server\target:/mnt/kraydel-platform
    entrypoint: java -jar -Dspring.profiles.active=local kraydel-server-1.0-SNAPSHOT.jar
    networks:
      bridge-net:
        ipv4_address: 169.69.69.8

  pushevet:
    image: openjdk:8-alpine
    container_name: pushevent
    working_dir: /mnt/kraydel-platform
    depends_on:
      - postgres
    volumes:
      - D:\data\kraydel\codebase1\kraydel\kraydel-platform\kraydel-pushevent\target:/mnt/kraydel-platform
    entrypoint: java -jar -Dspring.profiles.active=local kraydel-pushevent-1.0-SNAPSHOT.jar
    networks:
      bridge-net:
        ipv4_address: 169.69.69.9

  oauth:
    image: openjdk:8-alpine
    container_name: oauth
    networks:
      bridge-net:
        ipv4_address: 169.69.69.10
    working_dir: /mnt/kraydel-platform
    depends_on:
      - postgres
    volumes:
      - D:\data\kraydel\codebase1\kraydel\kraydel-platform\kraydel-oauth-server\target:/mnt/kraydel-platform
    entrypoint: java -jar -Dspring.profiles.active=local kraydel-oauth-server.jar

volumes:
  esb-conf:
  das-conf:
  pgdata:

networks:
  bridge-net:
    driver: bridge
    ipam:
      config:
        - subnet: 169.69.69.0/24