version: "3.0"
services:
  esb:
    image: docker.wso2.com/wso2esb:5.0.0
    container_name: esb

    ports:
      - 9443:9443
      - 8280:8280

    networks:
      bridge-net1:
        ipv4_address: 169.69.69.2

  das:
    image:  chinthakaak/wso2das:3.1.0
    container_name: das

    ports:
      - 9444:9444
      - 8281:8281

    networks:
      bridge-net:
        ipv4_address: 169.69.69.3

volumes:
  esb-conf:
  das-conf:

networks:
  bridge-net:
    driver: bridge
    ipam:
      config:
        - subnet: 169.69.69.0/24