version: "3.0"
services:
  lbl:
    image: nginx:latest
    container_name: lbl
#    deploy:            # deploy works only with swarm mode
#      repicas: 1
    networks:
      bridge-net1:
        ipv4_address: 169.69.69.2 # if we set a ip scaling will not be possible

    ports:
      - 80:80
      - 443:443
      - 9443:9443
      - 9444:9444

    volumes:
      - lbl-conf:/etc/nginx

  esb-mgr:
    image: docker.wso2.com/wso2esb:5.0.0
    container_name: esb-mgr
#    environment:
#        - STARTUP_ARGS=-Dsetup

    networks:
      bridge-net1:
        ipv4_address: 169.69.69.3 # if we set a ip scaling will not be possible

#    ports:
#      - 9443:9443
#      - 8280:8280

    volumes:
      - esb-mgr-conf:/opt/wso2esb-5.0.0/repository/conf

  esb-wkr1:
    image: docker.wso2.com/wso2esb:5.0.0
    container_name: esb-wkr1
#    environment:
#        - STARTUP_ARGS=-DworkerNode=true

    networks:
      bridge-net1:
        ipv4_address: 169.69.69.4 # if we set a ip scaling will not be possible

#    ports:
#      - 9443:9443
#      - 8280:8280

    volumes:
      - esb-wkr1-conf:/opt/wso2esb-5.0.0/repository/conf

  das-mgr:
    image:  chinthakaak/wso2das:3.1.0
    container_name: das-mgr

    networks:
      bridge-net1:
        ipv4_address: 169.69.69.5 # if we set a ip scaling will not be possible

    volumes:
      - das-mgr-conf:/opt/wso2das-3.1.0/repository/conf

  das-wkr1:
    image:  docker.wso2.com/wso2esb-analytics:5.0.0
    container_name: das-wkr1

    networks:
      bridge-net1:
        ipv4_address: 169.69.69.6
#
#    volumes:
#      - das-mgr-conf:/opt/wso2das-5.0.0/repository/conf
volumes:
  lbl-conf:
  esb-mgr-conf:
  esb-wkr1-conf:
  das-mgr-conf:

networks:
  bridge-net1:
    driver: bridge
    ipam:
      config:
        - subnet: 169.69.69.0/24