version: "3.0"
services:
  esb:
    image: docker.wso2.com/wso2esb:5.0.0
    container_name: esb
    ports:
      - 9443:9443
      - 8280:8280
    volumes:
      - D:\data\git_projects\krdl\volumes\esb\repository\components\lib:/mnt/wso2esb-5.0.0/repository/components/lib
      - D:\data\git_projects\krdl\volumes\esb\repository\conf\datasources:/mnt/wso2esb-5.0.0/repository/conf/datasources
      - D:\data\git_projects\krdl\volumes\esb\repository\deployment\server\carbonapps:/mnt/wso2esb-5.0.0/repository/deployment/server/carbonapps

  postgres:
    image: postgres:10.1
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: