version: "3.0"
services:
  esb-5:
    image: chinthakaak/wso2esb:wso2esb-5.0.0
    container_name: esb-5
    ports:
      - 9443:9443
      - 8280:8280
    volumes:
      - ./volumes/esb-5/repository/components/lib:/mnt/wso2esb-5.0.0/repository/components/lib
      - ./volumes/esb-5/repository/conf/datasources:/mnt/wso2esb-5.0.0/repository/conf/datasources
      - ./volumes/esb-5/repository/resources/security:/mnt/wso2esb-5.0.0/repository/resources/security
      - ./volumes/esb-5/repository/deployment/server/carbonapps:/mnt/wso2esb-5.0.0/repository/deployment/server/carbonapps