version: '3.3'
services:
  postgres:
    image: postgres:10.1
    container_name: postgres

    ports:
      - 5430:5432

    networks:
      bridge-net:
        ipv4_address: 169.169.69.61

networks:
  bridge-net:
    driver: bridge
    ipam:
      config:
        - subnet: 169.169.69.0/24