version: '3.3'
services:
  postgres:
    image: postgres:10.1
    container_name: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

    networks:
      bridge-net:
        ipv4_address: 169.169.69.61

volumes:
  pgdata:

networks:
  bridge-net:
    driver: bridge
    ipam:
      config:
        - subnet: 169.169.69.0/24