version: '3.3'
services:
  server:
    image: java:openjdk-8
    container_name: server
    working_dir: /mnt/kraydel-platform
    volumes:
      - D:\data\kraydel\codebase1\kraydel\kraydel-platform\kraydel-server\target:/mnt/kraydel-platform
    entrypoint: java -jar -Dspring.profiles.active=dev kraydel-server-1.0-SNAPSHOT.jar