version: "3.0"
services:
  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    ports:
      - 9000:9000
      - 9092:9092
    volumes:
      - ./volumes/sonar/data:/opt/sonarqube/data